### ISSUE TITLE
file upload error

### ISSUE THREAD

**Issue by TakatoG** [ohuelab/MEGADOCK-on-Colab#1]
Thank you for useful tool.
I have problem with uploading file.

In the first of this program,

from google.colab import files
#@markdown **Receptor PDB** (`-R`)
print("upload receptor PDB file (.pdb)")
rup = files.upload()
rfilename = list(rup.keys())[0]

and then 

---------------------------------------------------------------------------
MessageError                              Traceback (most recent call last)
[<ipython-input-7-a20c5ddfb56b>](https://o208apffe4-496ff2e9c6d22116-0-colab.googleusercontent.com/outputframe.html?vrz=colab_20231012-060150_RC00_572849617#) in <cell line: 4>()
      2 #@markdown **Receptor PDB** (`-R`)
      3 print("upload receptor PDB file (.pdb)")
----> 4 rup = files.upload()
      5 rfilename = list(rup.keys())[0]

3 frames
[/usr/local/lib/python3.10/dist-packages/google/colab/_message.py](https://o208apffe4-496ff2e9c6d22116-0-colab.googleusercontent.com/outputframe.html?vrz=colab_20231012-060150_RC00_572849617#) in read_reply_from_input(message_id, timeout_sec)
    101     ):
    102       if 'error' in reply:
--> 103         raise MessageError(reply['error'])
    104       return reply.get('data', None)
    105 

MessageError: RangeError: Maximum call stack size exceeded.

Maybe file upload error?
How can treat with this problem?

Thank you.

**Comment by tonets** [comment]
Thank you for using MEGADOCK-on-Colab. 
It has been reported that the file upload function of Google Colab may experience issues when using the Safari browser on Mac. Are you using Safari? If so, please try using Google Chrome.
https://stackoverflow.com/questions/53630073/google-colaboratory-import-data-stack-size-exceeded

Thank you so much.

**Comment by TakatoG** [comment]
Thank you very much！

**Comment by asegarrac** [comment]
I have a similar problem when uploading the files. I am using Google Chrome. 
MEGADOCK parameter setting
[26]
0 s

mv: cannot stat '/content/receptor.pdb': No such file or directory
mv: cannot stat '/content/ligand.pdb': No such file or directory

How can I fix this problem? 
Many thanks!
